spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://db-hello/hello_test
  application:
    name: hello-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: dorian.lan

application:
  instance: 1